apiVersion: v1
kind: Service
metadata:
  name: todo-app
  namespace: todo-app
  labels:
    app: todo-app
spec:
  # Lấy giá trị từ values.yaml (sẽ là ClusterIP)
  type: {{ .Values.service.type }}
  selector:
    app: todo-app
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
      protocol: TCP
      # Chỉ thêm nodePort nếu type là NodePort, còn ClusterIP thì bỏ qua
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}