apiVersion: v1
entries:
  todo-app:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2026-03-23T00:48:37.6949496+07:00"
    description: A Helm chart for Kubernetes
    digest: 337bc4983d0e9b365a827730794f03a17c11ac4952560df81b65b07543eee535
    name: todo-app
    type: application
    urls:
    - https://jfrog.ddthien.id.vn/artifactory/helm-local/todo-app-0.1.0.tgz
    version: 0.1.0
generated: "2026-03-23T00:48:37.6933421+07:00"
